name: Julia Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Setup dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.test()'

