name: Julia Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Cache Julia artifacts
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-artifacts-

      - name: Cache Julia compiled modules
        uses: actions/cache@v3
        with:
          path: ~/.julia/compiled
          key: ${{ runner.os }}-julia-compiled-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-compiled-

      - name: Install dependencies
        run: |
          julia --project=. -e '
          using Pkg;
          Pkg.instantiate();
          Pkg.precompile();
          '

      - name: Run tests
        run: |
          julia --project=. -e '
          using Pkg;
          Pkg.test(; test_args=["--project=."]);'