name: Julia Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Cache Julia artifacts
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-artifacts-

      - name: Install dependencies
        run: |
          julia --project=. -e '
          using Pkg;
          Pkg.instantiate();
          Pkg.precompile();
          '

      - name: Run tests with coverage
        run: |
          julia --project=. -e '
          using Pkg;
          Pkg.test(; coverage=true);
          '

      - name: Generate coverage report
        run: |
          julia --project=. -e '
          using Coverage;
          results = process_folder();
          LCOV.writefile("coverage.lcov", results);
          '

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: Code coverage
          fail_ci_if_error: true
